### ISSUE TITLE
[Feat]: Alert Configuration Management from Netdata Cloud

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata-cloud#779]
### Problem

Currently, there is no way to create / modify alert configurations from the Netdata Cloud UI.

### Description

The most important feature for our users to troubleshoot their infrastructure is the Alerts. Given that there is no way for users to create any alerts from the UI, they are relying on our default alerts which are not always tuned to individual user needs. Also, there is a need for our users to make the configuration changes on each of their node / agent and is error prone.

### Importance

must have

### Value proposition

1. Most of our free users are willing to pay for this feature and get on the Pro / Business plan based on this capability.
2. This is one of the major missing features in our product currently.

### Proposed implementation

Provide an easy way to create Netdata alerts from the UI. Based on recent technological advancements:

- We can use GPT API to generate alert configurations for our users
- The Alert Configuration tab can have a **+** icon on the right top corner to add new alerts
- On Clicking, the user should be able to select the metric / chart / dimension on which to generate the alerts
- Allow simple threshold based alerts and anomaly rate based alerts to be defined on the UI
- On selecting all the input parameters, we should be able to generate the alert configuration (in the new Yaml format) once @MrZammler and @stelfrag come up with this format
- For the first step, we can simply ask the users to copy the Yaml configuration and add it to their agents.
- As a next step (for the future) we should be able to push the configuration to the agents and reload-health - @ralphm and @stelfrag we will need some help on when and how such a communication can be established
- The new alert configured should show up in the Alert Configurations tab as a "user-defined" alert.

cc: @car12o @ralphm @stelfrag @shyamvalsan @ktsaou

**Comment by sashwathn** [comment]
The Alerts configuration Management feature will now cover 3 use-cases:

- Creating a new alert from any Chart
- Creating a new alert from the Alerts Tab (without knowing the context in advance)
- Editing an existing alert from the "Active Alerts" and "Alerts Configuration" tabs.

The tasks identified for this initiative are as follows:

** Design **
- [X] [UX / UI Design](https://www.figma.com/file/ONewmTVGItBH23ZctMGtsW/Alerts-Configuration?type=design&node-id=221-17418&t=2fCXURKyUYaQQyrA-0)
The ideation was done based on inputs and feedback [here](https://app.diagrams.net/#G1lq3CdiYm0y-S3JvglK1DReR-LOlNlINq)

** Backend **

- [x] Get all the fields from the agent alerts configurations and store them in the database to show them in relevant fields on the UI (for editing existing alerts)
- [x] API to render the list of all contexts available and collecting metrics
- [ ] API to render the list of aggregation methods (or static) - AVG, CV, STDDEV, MAX, MIN, etc
- [x] API to render all the dimensions in a context, individually and to select "All dimensions" with a single click
- [x] API to select the list of nodes where the alert is applicable
- [x] API to select the list of instances (charts) where the alert is applicable
- [x] API to select a label for which an alert is applicable
- [x] API to render the list of available variables usable in the alert calculation field (formula) - $dimension1, 2 3, $this, $now etc (Get the variables from the payload in the above call for dimensions list)
- [ ] API to Explain the generated alert configuration in human readable form (using OpenAI) - @shyamvalsan already has an initial version of this available
- [ ] API to send the alert configuration to the agent to "**Validate the Alert**" and send back a json to be able to plot on top of the existing chart

** Frontend **

- [ ] To replicate the design as per this mockup https://www.figma.com/proto/ONewmTVGItBH23ZctMGtsW/Alerts-Configuration?page-id=0%3A1&type=design&node-id=64-7583&viewport=247%2C325%2C0.25&scaling=min-zoom&starting-point-node-id=38%3A6149
- [ ] Static Dropdown if a user wants to create an alert on the "sum of" all or selected dimensions OR create an alert "for each" dimension selected.
- [ ] Static dropdown to select the OS for which the alert is applicable ( Only static to display linux or freebsd)
- [ ] Static rendering of default alert variables ($this, $now, etc) and aggregate them to the list of dimension variables.

** Agent **

- [x] Send all the content of Alerts configurations to the Cloud
- [ ] API to receive the alerts configuration from the Cloud and Test the Alert
- [ ] API to send the json to the Cloud with the "time frames" / "points" when the Alert would have been raised
- [ ] Central Configuration APIs to send configurations to the cloud

cc: @MrZammler @car12o @christophidesp @kapantzak

**Comment by kapantzak** [comment]
@sashwathn in case where we need to edit an existing alert configuration, we'll have to parse [expressions](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#expressions) in order to figure out how to fill the various fields in the configuration modal.

I guess, we'll may face more complex expressions than just `warn: $this > (75)`.

My question is how would the FE parse such an expression?

**Comment by ralphm** [comment]
I think we said that for now we'll leave the expression as free form, and not offer a [query builder](https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#builder-mode) like Grafana has.

That said, if the UI is going to parse these expressions, it would need to be consistent with how the Agent parses them. The Agent parses expressions with [this code](https://github.com/netdata/netdata/tree/master/libnetdata%2Feval). As you can see, this is a fully realized parser rather than one generated from a grammar. I think that it shouldn't be too hard to create a proper grammar from this code, and then generate the parsers for the Agent and the UI from that, to achieve consistency. The UI could use the same grammar for a full fledged builder. Eventually.

Alternatively, we could have an API on the Agent that parses expressions and then returns some kind of object structure, but that seems silly.

**Comment by kapantzak** [comment]
Just to make sure that I get it @ralphm , you say that we can create a parser that lives in the FE, according to [this code](https://github.com/netdata/netdata/tree/master/libnetdata%2Feval) that returns an object that we can then use n order to set the UI values.

Wouldn't that make things more complex in the future if we change the way that the Agent parser works? We will end up having to maintain this functionality in 2 places. (Maybe I got it wrong)

**Comment by ralphm** [comment]
No, I'm saying we define the expression grammar in a formal grammar language like Backus-Naur Form (BNF) or preferably Parsing Extension Grammar (PEG). Then both the Agent and UI need to use that as the basis for parsing. This allows you to define tests to verify both implement the same language.

However, if you later add to the language, both have to be updated accordingly. There is no magic to escape this.

**Comment by sashwathn** [comment]
> I guess, we'll may face more complex expressions than just `warn: $this > (75)`.

@kapantzak : For the expressions, we simply need to copy whatever is on the configuration lines: calc, warn, crit and represent them as a free text expression where it is not of the form `$this > (75)`.
I think @christophidesp was planning to add an advanced expression section under "warn" and "crit" as well which is a free text representing a formula and we will only provide a list of variables that can be used.

**Comment by kapantzak** [comment]
### Fixes needed for first iteration

- [x] `crit`/`warn`: add option for user to insert custom expression as free text, apart from the predefined component
- [x] `hosts`/`charts`: add option for user to insert custom expression apart from the dropdown options
- [x] `labels`: allow user to define key/value pairs
- [x] On selecting the nodes / hosts, it additionally adds the number of nodes in the end..
- [x] Same issue with instances selection.
- [x] The `chart labels` attribute is wrong. Replace `chartLabels` with `chart labels`
- [x] When the `lookup` chooses `EACH` with `All dimensions`, the `foreach *` is missing in the configuration.
- [x] The `send to` field is not being honoured if don't send clear notifications are ticked. These are independent options - anything in `Send to` should show up in the `to:` field.
- [x] The `Don't send clear notifications` if ticked should set the following option - `options: no-clear-notification`. 
- [ ] Support of host labels similar to chart labels provided it is available on the FE. ([https://learn.netdata.cloud/docs/alerting/health-configuration-reference#alert-line-host-labels](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#alert-line-host-labels))

**Comment by hugovalente-pm** [comment]
@sashwathn should this be closed and one or two new following tickets be opened for phase 2 (validate alerts) and 3 (send config to Agent from UI)?

**Comment by hugovalente-pm** [comment]
@sashwathn I'm closing this since ethe main piece is delivered
follow-ups to do validation and send configs should be tracked on a separate ticket
