### ISSUE TITLE
Integrate AR into Alerts

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata-cloud#802]
```[tasklist]
### Tasks
- [ ] https://github.com/netdata/netdata/issues/14701
- [ ] https://github.com/netdata/netdata-cloud/issues/757
- [ ] https://github.com/netdata/netdata-cloud/issues/759
- [ ] https://github.com/netdata/netdata/pull/14687
- [ ] https://github.com/netdata/netdata-cloud/issues/618
```
