### ISSUE TITLE
Cloud Events tab is missing properties and facets for Alert Type, Class, Component, Role

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata-cloud#888]
```[tasklist]
### Tasks
- [ ] https://github.com/netdata/feed-ontology/pull/49
- [x] Cloud Backend: hydrate events with Alert fields from alert config
- [x] Cloud Backend: implement facet filters and aggregations
- [x] UI: use new facets
```

**Comment by hugovalente-pm** [comment]
this is done
![image](https://github.com/netdata/netdata-cloud/assets/82235632/a68556dd-1201-4342-a813-f37faad6447f)
